spring.output.ansi.enabled=ALWAYS
spring.application.name=projeto_individual

spring.datasource.url=jdbc:mysql://localhost:3306/projeto_individual
spring.datasource.username=root
spring.datasource.password=@Jax10
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver